<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1556668810918" stop="1556668811115" version="1.4.0">
  <name>Magento\Sales\Test\Unit\Model\RefundOrderTest</name>
  <test-cases>
    <test-case start="1556668810919" stop="1556668811092" status="passed">
      <name>testOrderCreditmemo with data set "TestWithNotifyTrue"</name>
    </test-case>
    <test-case start="1556668811092" stop="1556668811101" status="passed">
      <name>testOrderCreditmemo with data set "TestWithNotifyFalse"</name>
    </test-case>
    <test-case start="1556668811101" stop="1556668811108" status="passed">
      <name>testDocumentValidationException</name>
    </test-case>
    <test-case start="1556668811108" stop="1556668811115" status="passed">
      <name>testCouldNotCreditmemoException</name>
    </test-case>
  </test-cases>
</alr:test-suite>
