<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1556668814236" stop="1556668814279" version="1.4.0">
  <name>Magento\Security\Test\Unit\Model\SecurityChecker\FrequencyTest</name>
  <test-cases>
    <test-case start="1556668814236" stop="1556668814242" status="passed">
      <name>testCheck with data set #0</name>
    </test-case>
    <test-case start="1556668814242" stop="1556668814245" status="passed">
      <name>testCheck with data set #1</name>
    </test-case>
    <test-case start="1556668814245" stop="1556668814248" status="passed">
      <name>testCheck with data set #2</name>
    </test-case>
    <test-case start="1556668814248" stop="1556668814251" status="passed">
      <name>testCheck with data set #3</name>
    </test-case>
    <test-case start="1556668814252" stop="1556668814254" status="passed">
      <name>testCheck with data set #4</name>
    </test-case>
    <test-case start="1556668814255" stop="1556668814258" status="passed">
      <name>testCheck with data set #5</name>
    </test-case>
    <test-case start="1556668814258" stop="1556668814261" status="passed">
      <name>testCheckException with data set #0</name>
    </test-case>
    <test-case start="1556668814262" stop="1556668814265" status="passed">
      <name>testCheckException with data set #1</name>
    </test-case>
    <test-case start="1556668814265" stop="1556668814268" status="passed">
      <name>testCheckException with data set #2</name>
    </test-case>
    <test-case start="1556668814269" stop="1556668814272" status="passed">
      <name>testCheckException with data set #3</name>
    </test-case>
    <test-case start="1556668814272" stop="1556668814275" status="passed">
      <name>testCheckException with data set #4</name>
    </test-case>
    <test-case start="1556668814276" stop="1556668814279" status="passed">
      <name>testCheckException with data set #5</name>
    </test-case>
  </test-cases>
</alr:test-suite>
