<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1556668662305" stop="1556668662311" version="1.4.0">
  <name>Magento\Setup\Test\Unit\Module\Di\App\Task\OperationFactoryTest</name>
  <test-cases>
    <test-case start="1556668662306" stop="1556668662308" status="passed">
      <name>testCreateSuccess with data set #0</name>
    </test-case>
    <test-case start="1556668662308" stop="1556668662309" status="passed">
      <name>testCreateSuccess with data set #1</name>
    </test-case>
    <test-case start="1556668662309" stop="1556668662310" status="passed">
      <name>testCreateSuccess with data set #2</name>
    </test-case>
    <test-case start="1556668662310" stop="1556668662311" status="passed">
      <name>testCreateException</name>
    </test-case>
  </test-cases>
</alr:test-suite>
