<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1556668683307" stop="1556668683336" version="1.4.0">
  <name>Magento\CatalogInventory\Test\Unit\Model\StockManagementTest</name>
  <test-cases>
    <test-case start="1556668683308" stop="1556668683321" status="passed">
      <name>testRegisterProductsSale with data set #0</name>
    </test-case>
    <test-case start="1556668683322" stop="1556668683327" status="passed">
      <name>testRegisterProductsSale with data set #1</name>
    </test-case>
    <test-case start="1556668683327" stop="1556668683332" status="passed">
      <name>testRegisterProductsSale with data set #2</name>
    </test-case>
    <test-case start="1556668683332" stop="1556668683336" status="passed">
      <name>testRegisterProductsSaleException with data set #0</name>
    </test-case>
  </test-cases>
</alr:test-suite>
